<img src="https://pandas.pydata.org/static/img/pandas.svg" width=200px>

# pandas DataFrames
---

[Watch a walk-through of this lesson on YouTube](https://youtu.be/OJP-L_M1vEs)

## Questions:
- How do I read in data from a file?
- How can I work with data in tabular format (tables)?
- How can I do basic descriptive statistics on tabular data?

## Learning Objectives:
- Select individual values from a Pandas dataframe
- Select entire rows or entire columns from a dataframe
- Select a subset of both rows and columns from a dataframe in a single operation
- Select a subset of a dataframe by a single Boolean criterion
- Obtain descriptive statistics for subsets of data within a table
- Use the split-apply-combine paradigm to work with data
---

## What is pandas?

Bad news first: there are no cute, black-and-white bears here. [pandas](https://pandas.pydata.org/docs/) (whose official name starts with a lower-case "p") is a Python *library* for working with data in a tabular format, such as is found in file formats like CSV, Microsoft Excel, and Google Sheets. Unlike Excel or Sheets, pandas is not a point-and click graphical interface for working with these files — everything is done through Python code. But compared to other formats for working with data that we have seen in this workshop, such as lists and dictionaries, pandas may seem more familiar, and it definitely lends itself more naturally to large data sets. Indeed, pandas' mission statement is, "...to be the fundamental high-level building block for doing practical, real world data analysis in Python". 

The primary units of pandas data storage you will work with are [DataFrames](https://pandas.pydata.org/pandas-docs/stable/getting_started/intro_tutorials/01_table_oriented.html#min-tut-01-tableoriented) (essentially, tables of data organized as rows and columns). DataFrames are actually collections of pandas [Series](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html) objects, which can be thought of as individual rows or columns (or vectors, or 1D arrays). 

Among the things that make pandas so attractive are the powerful interface to access individual records of the table, proper handling of missing values, and relational-databases operations between DataFrames. As well, pandas functions and methods are written to work intuitively and efficiently with data organized in tables. Most operations are *vectorized*, which means that they will automatically apply to all values in a DataFrame or Series without the need to write `for` loops to execute the same operation on a set of cells.

pandas is built on top of the [NumPy](https://numpy.org) library. Although we haven't discussed NumPy in this workshop, it is a powerful and widely used Python library for working with numerical data. However, it's worth noting for your future reference that most of the methods defined for NumPy Arrays also apply to Pandas Series/DataFrames.

## About Python Libraries

pandas is an example of a Python library. A **library** is a collection of files (called *modules*) that contains functions for use by other programs. Libraries provide ways of extending Python's functionality in different ways. They may also contain data values (e.g., numerical constants), entire sample data sets, and other things. A library's contents are supposed to be related, although there's no actual way to enforce that.

The Python [standard library](https://docs.python.org/3/library/) is an extensive suite of modules that comes with Python itself. Everything we've done so far in this workshop has been part of the standard library. Many additional libraries are available; CoCalc has a large number of extra libraries already installed.

To use a library in a particular Jupyter notebook or other Python program, we must import it using the `import` statement, like this:

~~~python
import pandas
~~~

Once a library is imported, we can use functions and methods from it. But, for functions we have to tell Python that the function can be found in a particular library we imported. For example, pandas has a function to import data from CSV (comma-separated value) files, called `read_csv`. To run this command, we would need to type:

~~~python
pandas.read_csv()
~~~

Since some package names are long, and adding the name to every function can result in a lot of typing, Python also allows us to assign an *alias* — a shorter name — to a library when we import it. For example, the convention for pandas is to give it the alias `pd` like this:

~~~python
import pandas as pd
~~~

Then to read a CSV file we could use:

~~~python
pd.read_csv()
~~~

In the cell below, import pandas with the alias pd:

In [2]:
import pandas as pd

## Importing data with pandas

As noted, we can read a CSV file and use it to create a pandas DataFrame, with the funciton `pd.read_csv()`. [CSV](https://en.wikipedia.org/wiki/Comma-separated_values) is a text format used for storing tabular data, in which each line of the file corresponds to a row in the table, and columns are separated with commas ("CSV" stands for "comma-separated values"). Often the first row of a CSV file will be the *header*, containing labels for each column. 

The Gapminder data is in CSV format, so let's load in one of the Gapminder datasets with the command below. Note that when we read in a DataFrame, we need to assign it to a variable name so that we can reference it later. A convention when working with pandas is to call the DataFrame `df`. This works fine if you only have one DataFrame to work with, although if you are working with multiple DataFrames it is a good idea to give them more meaningful names.

The Gapminder data are stored in a subfolder called `data`, so as the argument to `pd.read_csv()` below we give the folder name folled by a slash, then the file name:

~~~python
df = pd.read_csv('data/gapminder_gdp_europe.csv')
~~~

In [3]:
df = pd.read_csv('data/gapminder_gdp_europe.csv')

We can view the contents of the DataFrame `df` by simply typing its name and running the cell. Note that, unlike most of the examples we've used in previous lessons, we *don't* use the `print()` function. Although it works, the result is not nicely formatted the way the output is if we just use the name of the data frame.

That is, run this command: `df` — not `print(df)` — in the cell below.

In [4]:
df

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
1,Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
2,Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
3,Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
4,Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820
5,Croatia,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,11305.385170,13221.821840,13822.583940,8447.794873,9875.604515,11628.388950,14619.222720
6,Czech Republic,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,14297.021220,16048.514240,17596.210220,22833.308510
7,Denmark,9692.385245,11099.659350,13583.313510,15937.211230,18866.207210,20422.901500,21688.040480,25116.175810,26406.739850,29804.345670,32166.500060,35278.418740
8,Finland,6424.519071,7545.415386,9371.842561,10921.636260,14358.875900,15605.422830,18533.157610,21141.012230,20647.164990,23723.950200,28204.590570,33207.084400
9,France,7029.809327,8662.834898,10560.485530,12999.917660,16107.191710,18292.635140,20293.897460,22066.442140,24703.796150,25889.784870,28926.032340,30470.016700
10,Germany,7144.114393,10187.826650,12902.462910,14745.625610,18016.180270,20512.921230,22031.532740,24639.185660,26505.303170,27788.884160,30035.801980,32170.374420
11,Greece,3530.690067,4916.299889,6017.190733,8513.097016,12724.829570,14195.524280,15268.420890,16120.528390,17541.496340,18747.698140,22514.254800,27538.411880
12,Hungary,5263.673816,6040.180011,7550.359877,9326.644670,10168.656110,11674.837370,12545.990660,12986.479980,10535.628550,11712.776800,14843.935560,18008.944440
13,Iceland,7267.688428,9244.001412,10350.159060,13319.895680,15798.063620,19654.962470,23269.607500,26923.206280,25144.392010,28061.099660,31163.201960,36180.789190
14,Ireland,5210.280328,5599.077872,6631.597314,7655.568963,9530.772896,11150.981130,12618.321410,13872.866520,17558.815550,24521.947130,34077.049390,40675.996350
15,Italy,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,22013.644860,24675.024460,27968.098170,28569.719700
16,Montenegro,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,11222.587620,11732.510170,7003.339037,6465.613349,6557.194282,9253.896111
17,Netherlands,8941.571858,11276.193440,12790.849560,15363.251360,18794.745670,21209.059200,21399.460460,23651.323610,26790.949610,30246.130630,33724.757780,36797.933320
18,Norway,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170
19,Poland,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,7738.881247,10159.583680,12002.239080,15389.924680
20,Portugal,3068.319867,3774.571743,4727.954889,6361.517993,9022.247417,10172.485720,11753.842910,13039.308760,16207.266630,17641.031560,19970.907870,20509.647770
21,Romania,3144.613186,3943.370225,4734.997586,6470.866545,8011.414402,9356.397240,9605.314053,9696.273295,6598.409903,7346.547557,7885.360081,10808.475610
22,Serbia,3581.459448,4981.090891,6289.629157,7991.707066,10522.067490,12980.669560,15181.092700,15870.878510,9325.068238,7914.320304,7236.075251,9786.534714
23,Slovak Republic,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,9498.467723,12126.230650,13638.778370,18678.314350
24,Slovenia,4215.041741,5862.276629,7402.303395,9405.489397,12383.486200,15277.030170,17866.721750,18678.534920,14214.716810,17161.107350,20660.019360,25768.257590
25,Spain,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700
26,Sweden,8527.844662,9911.878226,12329.441920,15258.296970,17832.024640,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350
27,Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070
28,Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384
29,United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280

You'll see that the rows are numbered in boldface, starting with 0 as is the norm in Python. This boldfaced, leftmost column is called the **index** of the DataFrame, and provides one way of accessing data by rows. Across the top, you'll see that the column labels are also in boldface. pandas is pretty smart about automatically detecting when the first row of a CSV file contains header information (column names).

## Heads or Tails?

We might want to "peek" at the DataFrame without printing out the entire thing, especially if it's big. We can see the first 5 rows of a DataFrame with the `.head()` method:

~~~python
df.head()
~~~

In [5]:
df.head(7)

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
1,Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
2,Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
3,Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
4,Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820
5,Croatia,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,11305.385170,13221.821840,13822.583940,8447.794873,9875.604515,11628.388950,14619.222720
6,Czech Republic,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,14297.021220,16048.514240,17596.210220,22833.308510

...or the last 5 rows with `.tail()`:

In [6]:
df.tail()

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
25,Spain,3834.034742,4564.802410,5693.843879,7993.512294,10638.75131,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700
26,Sweden,8527.844662,9911.878226,12329.441920,15258.296970,17832.02464,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350
27,Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.11304,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070
28,Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.69638,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384
29,United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.11641,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280

We can also see a random sample of rows from the DataFrame with `.sample()`, giving it a numerical argument to indicate the number of rows we want to see:

~~~python
df.sample(10)
~~~

In [7]:
df.sample(15)

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
25,Spain,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700
27,Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070
22,Serbia,3581.459448,4981.090891,6289.629157,7991.707066,10522.067490,12980.669560,15181.092700,15870.878510,9325.068238,7914.320304,7236.075251,9786.534714
9,France,7029.809327,8662.834898,10560.485530,12999.917660,16107.191710,18292.635140,20293.897460,22066.442140,24703.796150,25889.784870,28926.032340,30470.016700
29,United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280
4,Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820
18,Norway,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170
15,Italy,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,22013.644860,24675.024460,27968.098170,28569.719700
3,Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
11,Greece,3530.690067,4916.299889,6017.190733,8513.097016,12724.829570,14195.524280,15268.420890,16120.528390,17541.496340,18747.698140,22514.254800,27538.411880
6,Czech Republic,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,14297.021220,16048.514240,17596.210220,22833.308510
2,Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
23,Slovak Republic,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,9498.467723,12126.230650,13638.778370,18678.314350
8,Finland,6424.519071,7545.415386,9371.842561,10921.636260,14358.875900,15605.422830,18533.157610,21141.012230,20647.164990,23723.950200,28204.590570,33207.084400
7,Denmark,9692.385245,11099.659350,13583.313510,15937.211230,18866.207210,20422.901500,21688.040480,25116.175810,26406.739850,29804.345670,32166.500060,35278.418740

Note that the `.head()` and `.tail()` methods also optionally take a numerical argument, if you want to view a different number of rows from the default of 5.

## Accessing values in a DataFrame

One thing we often want to do is access a single cell in a DataFrame, or a range of cells. Each cell is uniquely defined by a combination of its row and column locations.

### Select a column using `[]`

If we want to select an entire column of a pandas DataFrame, we just give the name of the DataFrame followed by the column name in square brackets:

~~~python
df['gdpPercap_1992']
~~~

In [8]:
df['country']

0                    Albania
1                    Austria
2                    Belgium
3     Bosnia and Herzegovina
4                   Bulgaria
5                    Croatia
6             Czech Republic
7                    Denmark
8                    Finland
9                     France
10                   Germany
11                    Greece
12                   Hungary
13                   Iceland
14                   Ireland
15                     Italy
16                Montenegro
17               Netherlands
18                    Norway
19                    Poland
20                  Portugal
21                   Romania
22                    Serbia
23           Slovak Republic
24                  Slovenia
25                     Spain
26                    Sweden
27               Switzerland
28                    Turkey
29            United Kingdom
Name: country, dtype: object

Note that if we ask for a single column the result is a pandas Series, but if we ask for two or more columns, the result is a DataFrame. Pay close attention to the syntax below — if we're asking for more than one column, we need to provide a *list* of columns inside the square brackets (so there are *two* sets of nested square brackets in the code below):

~~~python
df[['gdpPercap_1982', 'gdpPercap_1992']]
~~~

In [9]:
df[['country', 'gdpPercap_2002']]

                   country  gdpPercap_2002
0                  Albania     4604.211737
1                  Austria    32417.607690
2                  Belgium    30485.883750
3   Bosnia and Herzegovina     6018.975239
4                 Bulgaria     7696.777725
5                  Croatia    11628.388950
6           Czech Republic    17596.210220
7                  Denmark    32166.500060
8                  Finland    28204.590570
9                   France    28926.032340
10                 Germany    30035.801980
11                  Greece    22514.254800
12                 Hungary    14843.935560
13                 Iceland    31163.201960
14                 Ireland    34077.049390
15                   Italy    27968.098170
16              Montenegro     6557.194282
17             Netherlands    33724.757780
18                  Norway    44683.975250
19                  Poland    12002.239080
20                Portugal    19970.907870
21                 Romania     7885.360081
22                  Serbia     7236.075251
23         Slovak Republic    13638.778370
24                Slovenia    20660.019360
25                   Spain    24835.471660
26                  Sweden    29341.630930
27             Switzerland    34480.957710
28                  Turkey     6508.085718
29          United Kingdom    29478.999190

### Numerical indexing using `.iloc[]`

Often we don't want to access an entire column, however, but just specific rows within a column (or range of columns). pandas provides two ways of accessing cell locations. One is using the numerical positions in the DataFrame, using the convention of [row, column] — with [0, 0] being the top left cell in the DataFrame. So for a pandas DataFrame with 3 rows and 3 columns, the indices of each cell are as shown:

|   | col 0  | col 1  | col 2  | col 3  |
|---|--------|--------|--------|--------|
| 0 | [0, 0] | [0, 1] | [0, 2] | [0, 3] |
| 1 | [1, 0] | [1, 1] | [1, 2] | [1, 3] |
| 2 | [2, 0] | [2, 1] | [2, 2] | [2, 3] |
| 3 | [3, 0] | [3, 1] | [3, 2] | [3, 3] |


Numerical indexing of DataFrames is done with the `.iloc[]` method. For example, to access the GDP value for Austria in 1952 — which is located in the second row, third column of our current DataFrame, we would use:

~~~python
df.iloc[1, 2]
~~~

In [10]:
df.iloc[1,2]

np.float64(8842.59803)

## Label-based indexing using `.loc[]`

The other way to access a location in a DataFrame is by its index and column *labels*, using the `.loc[]` method. As noted earlier, in the DataFrame we imported, the indexes are currently numbers, which were created automatically when we imported the data. The `.loc[]` method doesn't work with numerical indexes (that's what `iloc` is for — and you can't mix, say, a numerical row index with a column label), but in the data set we imported, the first column of this CSV file is actually meant to be its index: while all other columns are data values (GDP, in type float), the first column identifies the country with which each row of data is associated. 

pandas has a method for setting an index column, `.set_index()`, where the argument (in the parentheses) would be the name of the column to use as the index. So here we want to run:

~~~python
df = df.set_index('country')
~~~

**Note** that we need to assign the result of this operation back to `df` (using `df = `), otherwise the change will not actually modify `df`.

In the cell below, use the `.set_index()` method to set the index of `df` to `country`, and then view the DataFrame again to see how it has changed.

In [11]:
df = df.set_index('country')
df.head()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820

Alternatively, if we knew which column we wanted to use as the index before loading in the data file, we could have included the argument `index_col=` in the `pd.read_csv()` command:

~~~python
df = pd.read_csv('data/gapminder_gdp_europe.csv', index_col='country')
~~~

Now that we have defined the index, we can access the 1952 GDP value for Austria by its index and column names:

~~~python
df.loc['Austria', 'gdpPercap_1952']
~~~

In [12]:
df.loc['Spain', 'gdpPercap_2002']

np.float64(24835.47166)

## Use `:` on its own to mean all columns or all rows.

Using Python's familiar slicing notation (which we've previously used for strings and lists), we can use `:` with `.iloc[]` or `.loc[]`, to specify a range in a DataFrame.

For example, to see the GDP of Albania for every year (column) in the DataFrame, we would use:

~~~python
df.loc["Albania", :]
~~~

In [13]:
df.loc['Albania', :]

gdpPercap_1952    1601.056136
gdpPercap_1957    1942.284244
gdpPercap_1962    2312.888958
gdpPercap_1967    2760.196931
gdpPercap_1972    3313.422188
gdpPercap_1977    3533.003910
gdpPercap_1982    3630.880722
gdpPercap_1987    3738.932735
gdpPercap_1992    2497.437901
gdpPercap_1997    3193.054604
gdpPercap_2002    4604.211737
gdpPercap_2007    5937.029526
Name: Albania, dtype: float64

Likewise, we could see the GDP for every country (row) in the year 1957 with:

~~~python
df.loc[:, 'gdpPercap_1957']
~~~

In [14]:
df.loc[:, 'gdpPercap_2002']

country
Albania                    4604.211737
Austria                   32417.607690
Belgium                   30485.883750
Bosnia and Herzegovina     6018.975239
Bulgaria                   7696.777725
Croatia                   11628.388950
Czech Republic            17596.210220
Denmark                   32166.500060
Finland                   28204.590570
France                    28926.032340
Germany                   30035.801980
Greece                    22514.254800
Hungary                   14843.935560
Iceland                   31163.201960
Ireland                   34077.049390
Italy                     27968.098170
Montenegro                 6557.194282
Netherlands               33724.757780
Norway                    44683.975250
Poland                    12002.239080
Portugal                  19970.907870
Romania                    7885.360081
Serbia                     7236.075251
Slovak Republic           13638.778370
Slovenia                  20660.019360
Spain                     24835.471660
Sweden                    29341.630930
Switzerland               34480.957710
Turkey                     6508.085718
United Kingdom            29478.999190
Name: gdpPercap_2002, dtype: float64

You can also just specify the row index; if you don't specify anything for the columns, pandas assumes you want all columns:

~~~python
df.loc["Albania"]
~~~

In [15]:
df.loc['Austria']

gdpPercap_1952     6137.076492
gdpPercap_1957     8842.598030
gdpPercap_1962    10750.721110
gdpPercap_1967    12834.602400
gdpPercap_1972    16661.625600
gdpPercap_1977    19749.422300
gdpPercap_1982    21597.083620
gdpPercap_1987    23687.826070
gdpPercap_1992    27042.018680
gdpPercap_1997    29095.920660
gdpPercap_2002    32417.607690
gdpPercap_2007    36126.492700
Name: Austria, dtype: float64

However, since the syntax for `.iloc[]` and `.loc[]` is [rows, columns], you cannot omit a row index; you need to use `:` if you want all rows.

## Slicing works on DataFrames

Slicing using numerical indices works similarly for DataFrames as we previously saw for strings and lists, for example, the following code will print the third through fifth rows of the DataFrame, and the fifth through eighth columns (remember, Python indexing starts at 0, and slicing does not include the "end" index): 

~~~python
df.iloc[2:5, 4:8]
~~~

In [16]:
df.iloc[2:5, 4:8]

,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987
country,,,,
Belgium,16672.143560,19117.974480,20979.845890,22525.563080
Bosnia and Herzegovina,2860.169750,3528.481305,4126.613157,4314.114757
Bulgaria,6597.494398,7612.240438,8224.191647,8239.854824

The code below will print from the sixth to second-last row of the DataFrame, and from the ninth to the last column:

~~~python
df.iloc[5:-1, 8:]
~~~

In [17]:
df.iloc[5:-1, 8:]

,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,
Croatia,8447.794873,9875.604515,11628.388950,14619.222720
Czech Republic,14297.021220,16048.514240,17596.210220,22833.308510
Denmark,26406.739850,29804.345670,32166.500060,35278.418740
Finland,20647.164990,23723.950200,28204.590570,33207.084400
France,24703.796150,25889.784870,28926.032340,30470.016700
Germany,26505.303170,27788.884160,30035.801980,32170.374420
Greece,17541.496340,18747.698140,22514.254800,27538.411880
Hungary,10535.628550,11712.776800,14843.935560,18008.944440
Iceland,25144.392010,28061.099660,31163.201960,36180.789190
Ireland,17558.815550,24521.947130,34077.049390,40675.996350
Italy,22013.644860,24675.024460,27968.098170,28569.719700
Montenegro,7003.339037,6465.613349,6557.194282,9253.896111
Netherlands,26790.949610,30246.130630,33724.757780,36797.933320
Norway,33965.661150,41283.164330,44683.975250,49357.190170
Poland,7738.881247,10159.583680,12002.239080,15389.924680
Portugal,16207.266630,17641.031560,19970.907870,20509.647770
Romania,6598.409903,7346.547557,7885.360081,10808.475610
Serbia,9325.068238,7914.320304,7236.075251,9786.534714
Slovak Republic,9498.467723,12126.230650,13638.778370,18678.314350
Slovenia,14214.716810,17161.107350,20660.019360,25768.257590
Spain,18603.064520,20445.298960,24835.471660,28821.063700
Sweden,23880.016830,25266.594990,29341.630930,33859.748350
Switzerland,31871.530300,32135.323010,34480.957710,37506.419070
Turkey,5678.348271,6601.429915,6508.085718,8458.276384

**Note** however, that when using label-based indexing with `.loc[]`, pandas' slicing behaviour is a bit different. Specifically, the output *includes* the last item in the range, whereas numerical indexing with `.iloc[]` does not. 

So, considering that the first three rows of the DataFrame correspond to the countries Albania, Austria, and Belgium, and that columns 6 and 7 are for the years 1982 and 1987 respectively, compare the output of:

~~~python
df.iloc[0:2, 6:7]
~~~

In [18]:
df.iloc[0:2, 6:7]

         gdpPercap_1982
country
Albania     3630.880722
Austria    21597.083620

with:

~~~python
df.loc['Albania':'Belgium', 'gdpPercap_1982':'gdpPercap_1988']
~~~

In [19]:
df.loc['Albania':'Belgium', 'gdpPercap_1982':'gdpPercap_1988']

         gdpPercap_1982  gdpPercap_1987
country
Albania     3630.880722     3738.932735
Austria    21597.083620    23687.826070
Belgium    20979.845890    22525.563080

The "inclusive" label-based indexing with `.loc[]` is fairly intuitive, but it's important to remember that it works differently from numerical indexing.

## Use lists to select non-contiguous sections of a DataFrame

While slicing can be very useful, sometimes we might want to extract values that aren't next to each other in a DataFrame. For example, what if we only want values from two specific years (1992 and 2002), for Scandinavian countries (Denmark, Finland, Norway, and Sweden)? Neither these years nor countries are in adjacent columns/rows in the DataFrame. With `.loc[]`, we can use lists, rather than ranges separated by `:`, as selectors:

~~~python
df.loc[['Denmark', 'Finland', 'Norway', 'Sweden'], ['gdpPercap_1992', 'gdpPercap_2002']]
~~~

In [20]:
df.loc[['Denmark', 'Spain', 'Finland'], ['gdpPercap_1992', 'gdpPercap_2002']]

         gdpPercap_1992  gdpPercap_2002
country
Denmark     26406.73985     32166.50006
Spain       18603.06452     24835.47166
Finland     20647.16499     28204.59057

We can equivalently write the command over several lines to make it a bit easier to read:

~~~python
df.loc[['Denmark', 'Finland', 'Norway', 'Sweden'], 
       ['gdpPercap_1992', 'gdpPercap_2002']
      ]
~~~

We could also define those lists as variables, and pass the variables to `.loc[]`. This might be useful if you were going to use the lists more than once, as well as for clarity:

~~~python
scand_countries = ['Denmark', 'Finland', 'Iceland', 'Norway', 'Sweden']
years = ['gdpPercap_1992', 'gdpPercap_2002']
df.loc[scand_countries, years]
~~~

In [21]:
scand_countries = ['Denmark', 'Finland', 'Iceland', 'Norway', 'Sweden']
years = ['gdpPercap_1992', 'gdpPercap_2002']
df.loc[scand_countries, years]

         gdpPercap_1992  gdpPercap_2002
country
Denmark     26406.73985     32166.50006
Finland     20647.16499     28204.59057
Iceland     25144.39201     31163.20196
Norway      33965.66115     44683.97525
Sweden      23880.01683     29341.63093

We can take this a step further, and assign the output of a `.loc[]` selection like this to a new variable name. This makes a copy of the selected data, stored in a new DataFrame (or Series, if we only select one row or column) with its own name. This allows us to later reference and use that selection. 

~~~python
scand_data = df.loc[scand_countries, years]
~~~

In [22]:
scand_data = df.loc[scand_countries, years]

## It's easy to do simple math and statistics in DataFrames

We prevoiusly learned about methods to get simple statistical values out of a Python list, like `.max()`, and `.min()`. pandas includes these and many more methods as well. For example, we can view the mean GDP for Italy across all years (columns) with:

~~~python
df.loc['Italy'].mean()
~~~

In [23]:
df.loc['Italy'].mean()

np.float64(16245.20900641667)

Or the largest GDP in 1977 with:

~~~python
df.loc[:, 'gdpPercap_1977'].max()
~~~

In [24]:
df.loc[:, 'gdpPercap_1977'].max()

np.float64(26982.29052)

Another useful method is `.describe()`, which prints out a range of descriptive statistics for the range of data you specify. Without any slicing it provides information for each column:

~~~python
df.describe()
~~~

In [25]:
df.describe()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,5661.057435,6963.012816,8365.486814,10143.823757,12479.575246,14283.979110,15617.896551,17214.310727,17061.568084,19076.781802,21711.732422,25054.481636
std,3114.060493,3677.950146,4199.193906,4724.983889,5509.691411,5874.464896,6453.234827,7482.957960,9109.804361,10065.457716,11197.355517,11800.339811
min,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
25%,3241.132406,4394.874315,5373.536612,6657.939047,9057.708094,10360.030300,11449.870115,12274.570680,8667.113214,9946.599306,11721.851483,14811.898210
50%,5142.469716,6066.721495,7515.733737,9366.067033,12326.379990,14225.754515,15322.824720,16215.485895,17550.155945,19596.498550,23674.863230,28054.065790
75%,7236.794919,9597.220820,10931.085348,13277.182058,16523.017127,19052.412163,20901.729730,23321.587723,25034.243045,27189.530312,30373.363307,33817.962533
max,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170

### Mini-Exercise
In the cell below, use the `scand_countries` and `years` variables to view descriptive statistics for all Scandinavian countries in each year.

In [26]:
scand_countries = ['Denmark', 'Finland', 'Iceland', 'Norway', 'Sweden']
years = ['gdpPercap_1992', 'gdpPercap_2002']
df.loc[scand_countries, years].describe()

       gdpPercap_1992  gdpPercap_2002
count        5.000000        5.000000
mean     26008.794966    33111.979754
std       4937.004264     6650.201977
min      20647.164990    28204.590570
25%      23880.016830    29341.630930
50%      25144.392010    31163.201960
75%      26406.739850    32166.500060
max      33965.661150    44683.975250

## Evaluate cells based on conditions

pandas allows an easy way to identify values in a DataFrame that meet a certain condition, using operators like `<`, `>`, and `==`. For example, let's see which countries in a list had a GDP over 10,000 in 1962 and 1992. The result is reported in Booleans (True/False) for each cell.

~~~python
countries = ['France', 'Germany', 'Italy', 'Spain', 'United Kingdom']
df.loc[countries, ['gdpPercap_1962', 'gdpPercap_1992']] > 10000
~~~

In [27]:
countries = ['France', 'Germany', 'Italy', 'Spain', 'United Kingdom']
df.loc[countries, ['gdpPercap_1962', 'gdpPercap_1992']] >10000

df.loc[:, 'gdpPercap_1992'] > 10000

country
Albania                   False
Austria                    True
Belgium                    True
Bosnia and Herzegovina    False
Bulgaria                  False
Croatia                   False
Czech Republic             True
Denmark                    True
Finland                    True
France                     True
Germany                    True
Greece                     True
Hungary                    True
Iceland                    True
Ireland                    True
Italy                      True
Montenegro                False
Netherlands                True
Norway                     True
Poland                    False
Portugal                   True
Romania                   False
Serbia                    False
Slovak Republic           False
Slovenia                   True
Spain                      True
Sweden                     True
Switzerland                True
Turkey                    False
United Kingdom             True
Name: gdpPercap_1992, dtype: bool

## Select values or NaN using a Boolean mask.

A DataFrame full of Booleans is sometimes called a *mask* because of how it can be used. A mask removes values that are not True, and replaces them with `NaN` — a special Python value representing "not a number". This can be useful because pandas ignores NaN values when doing computations. 

We create a mask by assigning the output of a conditional statement to a variable name:


~~~python
mask = scand_data > 30000
~~~

In [28]:
mask = scand_data > 30000

Then we can apply the mask to the DataFrame to get only the values that meet the criterion:

~~~python
scand_data[mask]
~~~

In [29]:
scand_data[mask]

         gdpPercap_1992  gdpPercap_2002
country
Denmark             NaN     32166.50006
Finland             NaN             NaN
Iceland             NaN     31163.20196
Norway      33965.66115     44683.97525
Sweden              NaN             NaN

As an example of how this might be used, the steps above would now allow us to find the lowest GDP value in each year, that was above 30,000:

~~~python
scand_data[mask].min()
~~~

In [30]:
scand_data[mask].min()

gdpPercap_1992    33965.66115
gdpPercap_2002    31163.20196
dtype: float64

## Split-Apply-Combine

A common task in data science is to split data into meaningful subgroups, apply an operation to each subgroup (e.g., compute the mean), and then combine the results into a single output, such as a table or a new DataFrame. This paradigm was famously [described by Hadley Wickham in a 2011 paper](http://dx.doi.org/10.18637/jss.v040.i01).

pandas provides methods and grouping operations that are very efficient (*vectorized*) for split-apply-combine operations.

As an example, let's say that we wanted to compare the average GDP for different regions of Europe, divided as northern, southern, eastern, and western. To do this, we first have to create lists defining the countries belonging to each of these regions:

~~~python
northern = ['Denmark', 'Finland', 'Iceland', 'Norway', 'Sweden']
southern = ['Greece', 'Italy', 'Portugal', 'Spain']
eastern = ['Albania', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 
            'Czech Republic', 'Hungary', 'Montenegro', 'Poland', 'Romania', 
            'Serbia', 'Slovak Republic', 'Slovenia']
western = ['Austria',  'Belgium', 'France', 'Germany', 'Ireland', 
            'Netherlands', 'Switzerland', 'United Kingdom']
~~~

In [31]:
northern = ['Denmark', 'Finland', 'Iceland', 'Norway', 'Sweden']
southern = ['Greece', 'Italy', 'Portugal', 'Spain']
eastern = ['Albania', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia',
            'Czech Republic', 'Hungary', 'Montenegro', 'Poland', 'Romania',
            'Serbia', 'Slovak Republic', 'Slovenia']
western = ['Austria',  'Belgium', 'France', 'Germany', 'Ireland',
            'Netherlands', 'Switzerland', 'United Kingdom']

Next we can make a new column simply by using `.loc[]` with the rows specified by one of the lists we just defined, a column name that doesn't already exist (in this case, we'll call it "region"), then assigning a region label to that combination of rows and column. We need to do this separately for each region. Note that when we first create the new column ("region"), pandas fills it with NaN values in any rows that were not defined by the assignment. For example, in the code below, the first line will create the column "region", and fill it with "northern" for any row in the `northern` list, and `NaN` to every other row. 

~~~python
df.loc[northern, 'region'] = 'northern'
df.loc[southern, 'region'] = 'southern'
df.loc[eastern, 'region'] = 'eastern'
df.loc[western, 'region'] = 'western'
~~~

In [32]:
df.loc[northern, 'region'] = 'northern'
df.loc[southern, 'region'] = 'southern'
df.loc[western, 'region'] = 'western'
df.loc[eastern, 'region'] = 'eastern'

### Split

Now we can use this "region" column to split the data into groups, using a pandas method called `.groupby()`

~~~python
grouped_countries = df.groupby('region')
~~~

In [33]:
grouped_countries = df.groupby('region')

Note that this step doesn't create a new DataFrame, it creates a special kind of pandas object that points to a grouping in the original DataFrame:

~~~python
type(grouped_countries)
~~~

In [34]:
type(grouped_countries)

pandas.core.groupby.generic.DataFrameGroupBy

### Apply

Now that we have split the data, we can apply a function separately to each group. Here we'll compute the mean GDP for each region, for each year:

~~~python
mean_gdp_by_region = grouped_countries.mean()
~~~

In [35]:
mean_gdp_by_region = grouped_countries.mean()

### Combine

The combine step actually occurred with the *apply* step above — the result is automatically combined into a table of mean values organized by region. But since our *apply* step (`.mean()`) saved the result to a variable, we can view the resulting table as the output of the *combine* step:

~~~python
mean_gdp_by_region
~~~

In [36]:
mean_gdp_by_region

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
region,,,,,,,,,,,,
eastern,3580.884612,4519.684445,5611.534264,6911.825724,8465.695242,10007.911765,10900.209963,11375.852107,8250.514199,9395.008143,10864.013821,14100.916656
northern,8401.571825,9890.985483,11817.031712,14359.783322,17164.045376,19570.072280,22091.364430,25661.659678,26008.794966,29627.830970,33111.979754,37576.646170
southern,3841.112208,4876.082568,6170.642960,8222.632153,11163.775519,12965.228980,14371.479317,16033.013775,18591.368087,20377.263280,23822.183125,26359.710762
western,8439.962345,10434.519899,12191.949119,14232.125299,17359.111144,19305.504057,20693.785153,22798.712417,25344.134586,27914.214806,31703.386229,35080.387365

### Chaining

In Python, **chaining** refers to combining a number of operations in one command, using a sequence of methods. We can perform the above split-apply-combine procedure in a single step as follows. Note that because we don't assign the output to a variable name, it is displayed as output but not saved.

~~~python
df.groupby('region').mean()
~~~

In [37]:
df.groupby('region').mean()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
region,,,,,,,,,,,,
eastern,3580.884612,4519.684445,5611.534264,6911.825724,8465.695242,10007.911765,10900.209963,11375.852107,8250.514199,9395.008143,10864.013821,14100.916656
northern,8401.571825,9890.985483,11817.031712,14359.783322,17164.045376,19570.072280,22091.364430,25661.659678,26008.794966,29627.830970,33111.979754,37576.646170
southern,3841.112208,4876.082568,6170.642960,8222.632153,11163.775519,12965.228980,14371.479317,16033.013775,18591.368087,20377.263280,23822.183125,26359.710762
western,8439.962345,10434.519899,12191.949119,14232.125299,17359.111144,19305.504057,20693.785153,22798.712417,25344.134586,27914.214806,31703.386229,35080.387365

---
# Exercises

## Selecting Individual Values

Write an expression to find the Per Capita GDP of Serbia in 2007.

In [38]:
df.loc['Serbia', 'gdpPercap_2007']

np.float64(9786.534714)

## Extent of Slicing

1.  Do the two statements below produce the same output? (Hint: you might want to use the `.head()` method to remind yourself of the structure of the DataFrame)
2.  Based on this, what rule governs what is included (or not) in numerical slices and named slices in Pandas?

~~~python
print(df.iloc[0:2, 0:2])
print(df.loc['Albania':'Belgium', 'gdpPercap_1952':'gdpPercap_1962'])
~~~

In [39]:
df.head()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007,region
country,,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526,eastern
Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700,western
Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080,western
Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803,eastern
Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820,eastern

## Reconstructing Data

Explain what each line in the following short program does:
what is in `df1`, `df2`, etc.?

~~~python
df1 = pd.read_csv('data/gapminder_all.csv', index_col='country')
df2 = df1[df1['continent'] == 'Americas']
df3 = df2.drop('Puerto Rico')
df4 = df3.drop('continent', axis = 1)
df4.to_csv('result.csv')
~~~

In [40]:
df1 = pd.read_csv('data/gapminder_all.csv', index_col='country')
df1.head()
df2 = df1[df1['continent'] == 'Americas']
df2.tail()
df3 = df2.drop('Puerto Rico')
df3.head()

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
country,,,,,,,,,,,,,,,,,,,,,
Argentina,Americas,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,...,21283783.0,22934225.0,24779799.0,26983828.0,29341374.0,31620918.0,33958947.0,36203463.0,38331121,40301927
Bolivia,Americas,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,...,3593918.0,4040665.0,4565872.0,5079716.0,5642224.0,6156369.0,6893451.0,7693188.0,8445134,9119152
Brazil,Americas,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,...,76039390.0,88049823.0,100840058.0,114313951.0,128962939.0,142938076.0,155975974.0,168546719.0,179914212,190010647
Canada,Americas,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,...,18985849.0,20819767.0,22284500.0,23796400.0,25201900.0,26549700.0,28523502.0,30305843.0,31902268,33390141
Chile,Americas,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,...,7961258.0,8858908.0,9717524.0,10599793.0,11487112.0,12463354.0,13572994.0,14599929.0,15497046,16284741

In [41]:
df4 = df3.drop('continent', axis = 1)
df4.head()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
country,,,,,,,,,,,,,,,,,,,,,
Argentina,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,...,21283783.0,22934225.0,24779799.0,26983828.0,29341374.0,31620918.0,33958947.0,36203463.0,38331121,40301927
Bolivia,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,...,3593918.0,4040665.0,4565872.0,5079716.0,5642224.0,6156369.0,6893451.0,7693188.0,8445134,9119152
Brazil,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,...,76039390.0,88049823.0,100840058.0,114313951.0,128962939.0,142938076.0,155975974.0,168546719.0,179914212,190010647
Canada,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,28954.925890,...,18985849.0,20819767.0,22284500.0,23796400.0,25201900.0,26549700.0,28523502.0,30305843.0,31902268,33390141
Chile,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,10118.053180,...,7961258.0,8858908.0,9717524.0,10599793.0,11487112.0,12463354.0,13572994.0,14599929.0,15497046,16284741

## Selecting Indices

Explain in simple terms what `idxmin` and `idxmax` do. When would you use these methods?

~~~python
data = pd.read_csv('data/gapminder_gdp_europe.csv', index_col='country')
data.idxmin()
~~~

In [42]:
data = pd.read_csv('data/gapminder_gdp_europe.csv', index_col='country')
data.idxmin()

gdpPercap_1952    Bosnia and Herzegovina
gdpPercap_1957    Bosnia and Herzegovina
gdpPercap_1962    Bosnia and Herzegovina
gdpPercap_1967    Bosnia and Herzegovina
gdpPercap_1972    Bosnia and Herzegovina
gdpPercap_1977    Bosnia and Herzegovina
gdpPercap_1982                   Albania
gdpPercap_1987                   Albania
gdpPercap_1992                   Albania
gdpPercap_1997                   Albania
gdpPercap_2002                   Albania
gdpPercap_2007                   Albania
dtype: object

~~~python
data.idxmax()
~~~

In [43]:
data.idxmax()

gdpPercap_1952    Switzerland
gdpPercap_1957    Switzerland
gdpPercap_1962    Switzerland
gdpPercap_1967    Switzerland
gdpPercap_1972    Switzerland
gdpPercap_1977    Switzerland
gdpPercap_1982    Switzerland
gdpPercap_1987         Norway
gdpPercap_1992         Norway
gdpPercap_1997         Norway
gdpPercap_2002         Norway
gdpPercap_2007         Norway
dtype: object

## Practice with Selection

From the previous exercise, the Gapminder GDP data for Europe should be loaded in as `data`. Using this DataFrame, write an expression to select each of the following:

- GDP per capita for all countries in 1982

In [45]:
data.loc[:, 'gdpPercap_1982']

country
Albania                    3630.880722
Austria                   21597.083620
Belgium                   20979.845890
Bosnia and Herzegovina     4126.613157
Bulgaria                   8224.191647
Croatia                   13221.821840
Czech Republic            15377.228550
Denmark                   21688.040480
Finland                   18533.157610
France                    20293.897460
Germany                   22031.532740
Greece                    15268.420890
Hungary                   12545.990660
Iceland                   23269.607500
Ireland                   12618.321410
Italy                     16537.483500
Montenegro                11222.587620
Netherlands               21399.460460
Norway                    26298.635310
Poland                     8451.531004
Portugal                  11753.842910
Romania                    9605.314053
Serbia                    15181.092700
Slovak Republic           11348.545850
Slovenia                  17866.721750
Spain                     13926.169970
Sweden                    20667.381250
Switzerland               28397.715120
Turkey                     4241.356344
United Kingdom            18232.424520
Name: gdpPercap_1982, dtype: float64

- GDP per capita for Denmark for all years

In [46]:
data.loc['Denmark', :]

gdpPercap_1952     9692.385245
gdpPercap_1957    11099.659350
gdpPercap_1962    13583.313510
gdpPercap_1967    15937.211230
gdpPercap_1972    18866.207210
gdpPercap_1977    20422.901500
gdpPercap_1982    21688.040480
gdpPercap_1987    25116.175810
gdpPercap_1992    26406.739850
gdpPercap_1997    29804.345670
gdpPercap_2002    32166.500060
gdpPercap_2007    35278.418740
Name: Denmark, dtype: float64

- GDP per capita for all countries for years *after* 1985

In [47]:
data.loc[:, 'gdpPercap_1985':]

,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,
Albania,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
Belgium,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
Bosnia and Herzegovina,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
Bulgaria,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820
Croatia,13822.583940,8447.794873,9875.604515,11628.388950,14619.222720
Czech Republic,16310.443400,14297.021220,16048.514240,17596.210220,22833.308510
Denmark,25116.175810,26406.739850,29804.345670,32166.500060,35278.418740
Finland,21141.012230,20647.164990,23723.950200,28204.590570,33207.084400
France,22066.442140,24703.796150,25889.784870,28926.032340,30470.016700
Germany,24639.185660,26505.303170,27788.884160,30035.801980,32170.374420
Greece,16120.528390,17541.496340,18747.698140,22514.254800,27538.411880
Hungary,12986.479980,10535.628550,11712.776800,14843.935560,18008.944440
Iceland,26923.206280,25144.392010,28061.099660,31163.201960,36180.789190
Ireland,13872.866520,17558.815550,24521.947130,34077.049390,40675.996350
Italy,19207.234820,22013.644860,24675.024460,27968.098170,28569.719700
Montenegro,11732.510170,7003.339037,6465.613349,6557.194282,9253.896111
Netherlands,23651.323610,26790.949610,30246.130630,33724.757780,36797.933320
Norway,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170
Poland,9082.351172,7738.881247,10159.583680,12002.239080,15389.924680
Portugal,13039.308760,16207.266630,17641.031560,19970.907870,20509.647770
Romania,9696.273295,6598.409903,7346.547557,7885.360081,10808.475610
Serbia,15870.878510,9325.068238,7914.320304,7236.075251,9786.534714
Slovak Republic,12037.267580,9498.467723,12126.230650,13638.778370,18678.314350
Slovenia,18678.534920,14214.716810,17161.107350,20660.019360,25768.257590
Spain,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700
Sweden,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350
Switzerland,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070
Turkey,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384
United Kingdom,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280

Note that pandas is smart enough to recognize the number at the end of the column label and does not give you an error, although no column named `gdpPercap_1985` actually exists. This is useful if new columns are added to the CSV file later.

- GDP per capita for each country in 2007 as a multiple of GDP per capita for that country in 1952

In [52]:
gdp2007 = data.loc[:, 'gdpPercap_2007']
gdp1952 = data.loc[:, 'gdpPercap_1952']
multiple_2007_1952 = gdp2007/gdp1952

print(multiple_2007_1952)

country
Albania                   3.708196
Austria                   5.886596
Belgium                   4.038377
Bosnia and Herzegovina    7.648736
Bulgaria                  4.369697
Croatia                   4.686795
Czech Republic            3.320658
Denmark                   3.639808
Finland                   5.168805
France                    4.334402
Germany                   4.503060
Greece                    7.799725
Hungary                   3.421364
Iceland                   4.978308
Ireland                   7.806873
Italy                     5.793425
Montenegro                3.495221
Netherlands               4.115376
Norway                    4.889067
Poland                    3.819475
Portugal                  6.684325
Romania                   3.437140
Serbia                    2.732555
Slovak Republic           3.680703
Slovenia                  6.113405
Spain                     7.517163
Sweden                    3.970493
Switzerland               2.545529
Turkey                    4.295502
United Kingdom            3.327144
dtype: float64

In [56]:
multiple_2007_1952 = data['gdpPercap_2007']/data['gdpPercap_1952']
print(multiple_2007_1952)

country
Albania                   3.708196
Austria                   5.886596
Belgium                   4.038377
Bosnia and Herzegovina    7.648736
Bulgaria                  4.369697
Croatia                   4.686795
Czech Republic            3.320658
Denmark                   3.639808
Finland                   5.168805
France                    4.334402
Germany                   4.503060
Greece                    7.799725
Hungary                   3.421364
Iceland                   4.978308
Ireland                   7.806873
Italy                     5.793425
Montenegro                3.495221
Netherlands               4.115376
Norway                    4.889067
Poland                    3.819475
Portugal                  6.684325
Romania                   3.437140
Serbia                    2.732555
Slovak Republic           3.680703
Slovenia                  6.113405
Spain                     7.517163
Sweden                    3.970493
Switzerland               2.545529
Turkey                    4.295502
United Kingdom            3.327144
dtype: float64

---
# Summary of Key Points:
- pandas DataFrames are a powerful way of storing and working with tabular (row/column) data
- pandas columns and rows can have names
- pandas row names are called *indexes* which are numeric by default, but can be given other labels
- Use the `.iloc[]` method with a DataFrame to select values by integer location, using [row, column] format
- Use the `.loc[]` method with a DataFrame to select rows and/or columns, using named slices
- Use `:` on its own to mean all columns or all rows
- Result of slicing can be used in further operations
- Use comparisons to select data based on value
- Select values or `NaN` using a Boolean mask
- use split-apply-combine to derive analytics from groupings within a DataFrame

---
This lesson is adapted from the [Software Carpentry](https://software-carpentry.org/lessons/) [Plotting and Programming in Python](http://swcarpentry.github.io/python-novice-gapminder/) workshop.